name: repo-all
on: 
  repository_dispatch:
jobs:
  ONE:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Echo Workflow and Action
        run: |
          echo "Workflow  = "${{ github.workflow }}
          echo "Action    = "${{ github.event.action }}
          echo "Function  = "${{ toJson(github.event.client_payload.function) }}
