name: myworkflow
on: 
  workflow_dispatch:
    inputs:
      p1:
      p2:
      filepath:
        required: true
        default: "./specs"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump Inputs
      env:
        INPUTS: ${{ toJson(github.event.inputs) }}
      run: |
        echo "$INPUTS"
    - name: Call Script implementing foo()
      env:
        INPUTS: ${{ toJson(github.event.inputs) }}
      run: |
        node ./handler.js "$INPUTS"
       